# Generated by Django 5.1.4 on 2024-12-28 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('ticker', models.CharField(max_length=10)),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('volume', models.BigIntegerField()),
                ('vwap', models.FloatField()),
            ],
            options={
                'indexes': [models.Index(fields=['timestamp', 'ticker'], name='backtesting_timesta_8812d6_idx')],
            },
        ),
    ]
