# Generated by Django 5.1.4 on 2024-12-29 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtesting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdata',
            name='vwap',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='stockdata',
            unique_together={('ticker', 'timestamp')},
        ),
    ]
